sonar.projectKey=testgenai-group11
sonar.projectName=TestGenAI Grupo 11
sonar.sources=backend/src,frontend/js
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
