// ==========================================================================
// Catálogo Determinista: Actores del Dominio
// Cada actor se detecta por palabras clave normalizadas (sin acentos).
// Las etiquetas están redactadas en masculino genérico para encajar en
// plantillas del tipo "El {ACTOR} ...".
// ==========================================================================

import { ActorDefinition } from '../spec-types';

export const DEFAULT_PRIMARY_ACTOR_KEY = 'usuario';
export const DEFAULT_ADMIN_ACTOR_KEY = 'administrador';

export const ACTOR_CATALOG: ActorDefinition[] = [
  {
    key: 'usuario',
    label: 'Usuario',
    description: 'Persona autenticada que utiliza las funciones principales del sistema.',
    keywords: ['usuario', 'usuarios', 'usuaria', 'usuarias', 'user', 'users'],
  },
  {
    key: 'administrador',
    label: 'Administrador',
    description: 'Responsable de configurar el sistema, gestionar cuentas, roles y catálogos maestros.',
    keywords: [
      'administrador',
      'administradores',
      'administradora',
      'admin',
      'superusuario',
      'super usuario',
    ],
    isAdmin: true,
  },
  {
    key: 'cliente',
    label: 'Cliente',
    description: 'Consumidor final que compra, reserva o solicita servicios a través del sistema.',
    keywords: [
      'cliente',
      'clientes',
      'comprador',
      'compradores',
      'consumidor',
      'consumidores',
      'huesped',
      'huespedes',
      'comensal',
      'comensales',
    ],
  },
  {
    key: 'vendedor',
    label: 'Vendedor',
    description: 'Personal comercial que atiende ventas, cotizaciones y seguimiento de clientes.',
    keywords: [
      'vendedor',
      'vendedores',
      'vendedora',
      'asesor de ventas',
      'asesores de ventas',
      'ejecutivo de ventas',
      'fuerza de ventas',
      'agente comercial',
      'asesor comercial',
    ],
  },
  {
    key: 'cajero',
    label: 'Cajero',
    description: 'Operador de caja que registra cobros, emite comprobantes y realiza arqueos.',
    keywords: ['cajero', 'cajeros', 'cajera', 'punto de venta', 'pos'],
  },
  {
    key: 'gerente',
    label: 'Gerente',
    description: 'Tomador de decisiones que consulta indicadores, reportes y aprueba operaciones críticas.',
    keywords: [
      'gerente',
      'gerentes',
      'gerencia',
      'director',
      'directores',
      'directora',
      'jefe',
      'jefes',
      'jefa',
      'dueño',
      'dueno',
      'propietario',
      'propietaria',
    ],
  },
  {
    key: 'supervisor',
    label: 'Supervisor',
    description: 'Responsable de coordinar equipos, validar tareas y aprobar solicitudes.',
    keywords: ['supervisor', 'supervisores', 'supervisora', 'coordinador', 'coordinadores', 'coordinadora'],
  },
  {
    key: 'operador',
    label: 'Operador',
    description: 'Personal operativo que ejecuta tareas diarias de registro y atención.',
    keywords: ['operador', 'operadores', 'operadora', 'operario', 'operarios'],
  },
  {
    key: 'medico',
    label: 'Médico',
    description: 'Profesional de salud que registra atenciones, diagnósticos y tratamientos.',
    keywords: [
      'medico',
      'medicos',
      'medica',
      'doctor',
      'doctores',
      'doctora',
      'especialista',
      'especialistas',
      'odontologo',
      'odontologa',
      'veterinario',
      'veterinaria',
      'psicologo',
      'psicologa',
      'nutricionista',
      'terapeuta',
    ],
  },
  {
    key: 'paciente',
    label: 'Paciente',
    description: 'Persona que recibe atención de salud y gestiona sus citas e historial.',
    keywords: ['paciente', 'pacientes'],
  },
  {
    key: 'enfermera',
    label: 'Personal de enfermería',
    description: 'Apoya el triaje, registro de signos vitales y seguimiento del paciente.',
    keywords: ['enfermera', 'enfermero', 'enfermeria', 'enfermeras', 'enfermeros'],
  },
  {
    key: 'recepcionista',
    label: 'Recepcionista',
    description: 'Atiende la recepción, agenda citas y registra el ingreso de personas.',
    keywords: ['recepcionista', 'recepcion', 'secretaria', 'secretario', 'asistente administrativo'],
  },
  {
    key: 'estudiante',
    label: 'Estudiante',
    description: 'Persona matriculada que accede a cursos, notas, asistencia y materiales.',
    keywords: [
      'estudiante',
      'estudiantes',
      'alumno',
      'alumnos',
      'alumna',
      'alumnas',
      'aprendiz',
      'aprendices',
      'participante',
      'participantes',
    ],
  },
  {
    key: 'docente',
    label: 'Docente',
    description: 'Imparte cursos, registra calificaciones y controla la asistencia.',
    keywords: [
      'docente',
      'docentes',
      'profesor',
      'profesores',
      'profesora',
      'maestro',
      'maestra',
      'maestros',
      'instructor',
      'instructores',
      'tutor',
      'tutores',
      'capacitador',
    ],
  },
  {
    key: 'apoderado',
    label: 'Padre o apoderado',
    description: 'Responsable legal que consulta el avance académico del estudiante.',
    keywords: ['apoderado', 'apoderados', 'padre de familia', 'padres de familia', 'tutor legal'],
  },
  {
    key: 'repartidor',
    label: 'Repartidor',
    description: 'Ejecuta entregas, actualiza estados de envío y registra evidencias.',
    keywords: [
      'repartidor',
      'repartidores',
      'motorizado',
      'motorizados',
      'courier',
      'mensajero',
      'mensajeros',
      'conductor',
      'conductores',
      'chofer',
      'choferes',
      'transportista',
      'transportistas',
      'delivery',
    ],
  },
  {
    key: 'proveedor',
    label: 'Proveedor',
    description: 'Entidad externa que abastece productos o servicios al negocio.',
    keywords: ['proveedor', 'proveedores', 'proveedora'],
  },
  {
    key: 'almacenero',
    label: 'Encargado de almacén',
    description: 'Controla ingresos, salidas y existencias físicas del inventario.',
    keywords: [
      'almacenero',
      'almacenista',
      'encargado de almacen',
      'jefe de almacen',
      'personal de almacen',
      'logistica',
    ],
  },
  {
    key: 'contador',
    label: 'Contador',
    description: 'Registra y concilia operaciones financieras y contables.',
    keywords: ['contador', 'contadora', 'contadores', 'contabilidad', 'tesorero', 'tesoreria', 'finanzas'],
  },
  {
    key: 'auditor',
    label: 'Auditor',
    description: 'Revisa la trazabilidad, bitácoras y cumplimiento de las operaciones.',
    keywords: ['auditor', 'auditores', 'auditora', 'auditoria'],
  },
  {
    key: 'agente_soporte',
    label: 'Agente de soporte',
    description: 'Atiende tickets, incidencias y consultas de los usuarios.',
    keywords: [
      'agente de soporte',
      'soporte tecnico',
      'mesa de ayuda',
      'helpdesk',
      'tecnico',
      'tecnicos',
      'agente',
      'agentes',
    ],
  },
  {
    key: 'mesero',
    label: 'Mesero',
    description: 'Toma pedidos en mesa y coordina con cocina y caja.',
    keywords: ['mesero', 'meseros', 'mesera', 'mozo', 'mozos', 'camarero', 'camareros', 'camarera'],
  },
  {
    key: 'cocinero',
    label: 'Cocinero',
    description: 'Prepara los pedidos recibidos desde la comanda.',
    keywords: ['cocinero', 'cocineros', 'cocina', 'chef'],
  },
  {
    key: 'empleado',
    label: 'Empleado',
    description: 'Colaborador interno que registra asistencia, solicitudes y tareas.',
    keywords: [
      'empleado',
      'empleados',
      'empleada',
      'trabajador',
      'trabajadores',
      'trabajadora',
      'colaborador',
      'colaboradores',
      'personal',
    ],
  },
  {
    key: 'rrhh',
    label: 'Analista de recursos humanos',
    description: 'Gestiona contratos, planillas, vacaciones y evaluaciones del personal.',
    keywords: ['recursos humanos', 'rrhh', 'rr hh', 'talento humano', 'planillas', 'planilla', 'nomina'],
  },
  {
    key: 'visitante',
    label: 'Visitante',
    description: 'Persona no autenticada que navega el contenido público.',
    keywords: [
      'visitante',
      'visitantes',
      'invitado',
      'invitados',
      'publico en general',
      'anonimo',
      'sin registrarse',
    ],
  },
  {
    key: 'socio',
    label: 'Socio',
    description: 'Miembro afiliado con beneficios, cuotas y membresías.',
    keywords: [
      'socio',
      'socios',
      'socia',
      'miembro',
      'miembros',
      'afiliado',
      'afiliados',
      'asociado',
      'asociados',
    ],
  },
  {
    key: 'sistema_externo',
    label: 'Sistema externo',
    description: 'Aplicación de terceros que se integra mediante API o archivos.',
    keywords: [
      'sistema externo',
      'sistemas externos',
      'integracion',
      'integraciones',
      'api',
      'webhook',
      'erp',
      'crm',
      'pasarela',
    ],
  },
];

export function findActor(key: string): ActorDefinition | undefined {
  return ACTOR_CATALOG.find((a) => a.key === key);
}
